// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekatWeb.Models;

namespace ProjekatWeb.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    [Migration("20210320195015_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjekatWeb.Models.Biblioteka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojPolica")
                        .HasColumnType("int")
                        .HasColumnName("BrojPolica");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Biblioteka");
                });

            modelBuilder.Entity("ProjekatWeb.Models.Knjiga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Autor");

                    b.Property<int>("BrojStrana")
                        .HasColumnType("int")
                        .HasColumnName("BrojStrana");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.Property<int?>("PolicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PolicaID");

                    b.ToTable("Knjiga");
                });

            modelBuilder.Entity("ProjekatWeb.Models.Polica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BibliotekaID")
                        .HasColumnType("int");

                    b.Property<int>("MaxBroj")
                        .HasColumnType("int")
                        .HasColumnName("MaxBroj");

                    b.Property<string>("Oznaka")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Oznaka");

                    b.Property<int>("TrenutniBroj")
                        .HasColumnType("int")
                        .HasColumnName("TrenutniBroj");

                    b.HasKey("ID");

                    b.HasIndex("BibliotekaID");

                    b.ToTable("Polica");
                });

            modelBuilder.Entity("ProjekatWeb.Models.Knjiga", b =>
                {
                    b.HasOne("ProjekatWeb.Models.Polica", "Polica")
                        .WithMany("Knjige")
                        .HasForeignKey("PolicaID");

                    b.Navigation("Polica");
                });

            modelBuilder.Entity("ProjekatWeb.Models.Polica", b =>
                {
                    b.HasOne("ProjekatWeb.Models.Biblioteka", "Biblioteka")
                        .WithMany("Police")
                        .HasForeignKey("BibliotekaID");

                    b.Navigation("Biblioteka");
                });

            modelBuilder.Entity("ProjekatWeb.Models.Biblioteka", b =>
                {
                    b.Navigation("Police");
                });

            modelBuilder.Entity("ProjekatWeb.Models.Polica", b =>
                {
                    b.Navigation("Knjige");
                });
#pragma warning restore 612, 618
        }
    }
}
